version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - sss_db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - SSS-network

  wordpress:
    depends_on:
      - db
    image: wordpress:5.6.0-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - sss_wp-content:/var/www/html
    networks:
      - SSS-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.19.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - sss_wp-content:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - SSS-network


volumes:
  sss_wp-content:
  sss_db:

networks:
  SSS-network:
    driver: bridge
